create table goals (
    GOAL_ID VARCHAR PRIMARY KEY,
	MATCH_ID VARCHAR,
	PID VARCHAR,
	DURATION INT,
	ASSIST VARCHAR,
	GOAL_DESC VARCHAR
);
COPY goals FROM 'C:\Program Files\PostgreSQL\17\pgAdmin 4\sql tables\goals.csv' CSV HEADER;

CREATE TABLE Matches (
    MATCH_ID VARCHAR PRIMARY KEY,
	SEASON VARCHAR,
	DATE VARCHAR,
	HOME_TEAM VARCHAR,
	AWAY_TEAM VARCHAR,
	STADIUM VARCHAR,
	HOME_TEAM_SCORE INT,
	AWAY_TEAM_SCORE INT,
	PENALTY_SHOOT_OUT INT,
	ATTENDANCE INT
	
);
COPY Matches FROM 'C:\Program Files\PostgreSQL\17\pgAdmin 4\sql tables\Matches.csv' CSV HEADER;

CREATE TABLE Players (
    PLAYER_ID VARCHAR PRIMARY KEY,
	FIRST_NAME VARCHAR,
	LAST_NAME VARCHAR,
	NATIONALITY VARCHAR,
	DOB DATE,
	TEAM VARCHAR,
	JERSEY_NUMBER FLOAT,
	POSITIONS VARCHAR,
	HEIGHT FLOAT,
	WEIGHT FLOAT,
	FOOT VARCHAR
);
COPY Players FROM 'C:\Program Files\PostgreSQL\17\pgAdmin 4\sql tables\Players.csv' CSV HEADER;

CREATE TABLE Teams (
    TEAM_NAME VARCHAR,
	COUNTRY VARCHAR,
	HOME_STADIUM VARCHAR
);
COPY Teams FROM 'C:\Program Files\PostgreSQL\17\pgAdmin 4\sql tables\Teams.csv' CSV HEADER;

CREATE TABLE Stadium (
    NAME_S VARCHAR,
	CITY VARCHAR,
	COUNTRY VARCHAR,
	CAPACITY INT
);
COPY Stadium FROM 'C:\Program Files\PostgreSQL\17\pgAdmin 4\sql tables\Stadiums.csv' CSV HEADER;